import GNB from "@/components/gnb";
import "@/styles/globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Codi It",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          href="https://cdn.rawgit.com/moonspam/NanumSquare/master/nanumsquare.css"
          rel="stylesheet"
        />
        {/* 포트원 SDK 로드 */}
        <Script src="https://cdn.iamport.kr/v1/iamport.js" />
      </head>
      <body>
        <Providers>
          <GNB />
          <main className="pt-20">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
